export const books = [
  {
    image: "Covers/TsarOfLove&Techno.jpg",
    title: "The Tsar of Love and Techno",
    author: "Anothony Marra",
    pages: 352,
    meetingDate: "5/28/2025",
    meetingLink: "",
    isCurrent: 1,
    member: "Peter",
  },
  {
    image: "Covers/SirensOfTitan.jpg",
    title: "Sirens of Titan",
    author: "Kurt Vonnegut",
    pages: 336,
    meetingDate: "4/18/2025",
    meetingLink: "",
    isCurrent: 0,
    member: "Kevin",
  },
  {
    image: "Covers/James.jpg",
    title: "James",
    author: "Percival Everett",
    pages: 320,
    meetingDate: "12/10/2024",
    meetingLink: "",
    isCurrent: 0,
    member: "Shannon",
  },
  {
    image: "Covers/Neuromancer.jpg",
    title: "Neuromancer",
    author: "William Gibson",
    pages: 336,
    meetingDate: "12/10/2024",
    meetingLink: "",
    isCurrent: 0,
    member: "Rylei",
  },
  {
    image: "Covers/AWalkInTheWoods.jpg",
    title: "A Walk in the Woods",
    author: "Bill Bryson",
    pages: 276,
    meetingDate: "12/10/2024",
    meetingLink: "",
    isCurrent: 0,
    member: "Monika",
  },
  {
    image: "Covers/3BodyProblem.jpg",
    title: "The Three Body Problem",
    author: "Cixin Liu",
    pages: 416,
    meetingDate: "11/9/2024",
    meetingLink: "",
    isCurrent: 0,
    member: "Derek",
  },
  {
    image: "Covers/10thOfDecember.jpg",
    title: "10th of December",
    author: "George Saunders",
    pages: 288,
    meetingDate: "10/10/2024",
    meetingLink: "",
    isCurrent: 0,
    member: "Peter",
  },
  {
    image: "Covers/TheSongOfAchilles.jpg",
    title: "The Song of Achilles",
    author: "Madeline Miller",
    pages: 369,
    meetingDate: "08/15/2024",
    meetingLink: "",
    isCurrent: 0,
    member: "Kevin",
  },
  {
    image: "Covers/TheWindKnowsMyName.jpg",
    title: "The Wind Knows My Name",
    author: "Isabel Allende",
    pages: 273,
    meetingDate: "07/25/2024",
    meetingLink: "",
    isCurrent: 0,
    member: "Shannon",
  },
  {
    image: "Covers/ThePrincessBride.jpg",
    title: "The Princess Bride",
    author: "William Goldman",
    pages: 512,
    meetingDate: "06/11/2024",
    meetingLink: "",
    isCurrent: 0,
    member: "Rylei",
  },
];

export const members = [
  { name: "Monika", id: 1, isActive: 1, isCurrent: 0, isNext: 0 },
  { name: "Rylei", id: 2, isActive: 1, isCurrent: 0, isNext: 0 },
  { name: "Shannon", id: 3, isActive: 1, isCurrent: 0, isNext: 0 },
  { name: "Kevin", id: 4, isActive: 1, isCurrent: 0, isNext: 0 },
  { name: "Peter", id: 5, isActive: 1, isCurrent: 1, isNext: 0 },
  { name: "Derek", id: 6, isActive: 1, isCurrent: 0, isNext: 1 },
];
